resources:
 pipelines:
   - pipeline: P1
     source: akshansh04.Test2-1
#  Random

stages:
 - stage: ProduceArtifact
   jobs:
     - job: J4
       pool: 
        name: Default
       steps:
         - download: P1
          #  artifact: A1.1
         - task: PublishBuildArtifacts@1
           inputs:
            PathtoPublish: 'artifact3'
            ArtifactName: 'A3_Project2'
            publishLocation: 'Container'
        #  - powershell: |
        #     ls $(Build.ArtifactStagingDirectory)/
